name: spendi-tests

services:
  db:
    image: postgres:14.19
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    ports:
      - "5433:5432"
